# Generated by Django 4.1.3 on 2022-11-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
