# Generated by Django 4.1.4 on 2022-12-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_delete_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bibliography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sourceFive',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sourceFour',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sourceOne',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sourceThree',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sourceTwo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
