# Generated by Django 4.1.4 on 2022-12-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_bibliography_article_sourcefive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
    ]
