# Generated by Django 4.1.4 on 2022-12-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Updated'),
        ),
    ]
