# Generated by Django 4.1.4 on 2023-01-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
