# Generated by Django 4.1.5 on 2023-01-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('science', 'Science'), ('politics', 'Politics'), ('health', 'Health'), ('arts', 'Arts'), ('sports', 'Sports'), ('business', 'Business'), ('world', 'World'), ('opinion', 'Opinion')], max_length=40, null=True),
        ),
    ]
