# Generated by Django 4.1.5 on 2023-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_categories_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sourceFiveOrg',
            field=models.CharField(blank=True, choices=[('CNN', 'CNN'), ('FOX', 'FOX'), ('NPR', 'NPR'), ('AP', 'AP'), ('MSNBC', 'MSNBC'), ('ABC', 'ABC'), ('CBS', 'CBS'), ('CNBC', 'CNBC'), ('NBC', 'NBC'), ('VICE', 'VICE'), ('BBC', 'BBC'), ('ESPN', 'ESPN'), ('other', 'Other')], default='other', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sourceFourOrg',
            field=models.CharField(blank=True, choices=[('CNN', 'CNN'), ('FOX', 'FOX'), ('NPR', 'NPR'), ('AP', 'AP'), ('MSNBC', 'MSNBC'), ('ABC', 'ABC'), ('CBS', 'CBS'), ('CNBC', 'CNBC'), ('NBC', 'NBC'), ('VICE', 'VICE'), ('BBC', 'BBC'), ('ESPN', 'ESPN'), ('other', 'Other')], default='other', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sourceOneOrg',
            field=models.CharField(blank=True, choices=[('CNN', 'CNN'), ('FOX', 'FOX'), ('NPR', 'NPR'), ('AP', 'AP'), ('MSNBC', 'MSNBC'), ('ABC', 'ABC'), ('CBS', 'CBS'), ('CNBC', 'CNBC'), ('NBC', 'NBC'), ('VICE', 'VICE'), ('BBC', 'BBC'), ('ESPN', 'ESPN'), ('other', 'Other')], default='other', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sourceThreeOrg',
            field=models.CharField(blank=True, choices=[('CNN', 'CNN'), ('FOX', 'FOX'), ('NPR', 'NPR'), ('AP', 'AP'), ('MSNBC', 'MSNBC'), ('ABC', 'ABC'), ('CBS', 'CBS'), ('CNBC', 'CNBC'), ('NBC', 'NBC'), ('VICE', 'VICE'), ('BBC', 'BBC'), ('ESPN', 'ESPN'), ('other', 'Other')], default='other', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sourceTwoOrg',
            field=models.CharField(blank=True, choices=[('CNN', 'CNN'), ('FOX', 'FOX'), ('NPR', 'NPR'), ('AP', 'AP'), ('MSNBC', 'MSNBC'), ('ABC', 'ABC'), ('CBS', 'CBS'), ('CNBC', 'CNBC'), ('NBC', 'NBC'), ('VICE', 'VICE'), ('BBC', 'BBC'), ('ESPN', 'ESPN'), ('other', 'Other')], default='other', max_length=10, null=True),
        ),
    ]
