# Generated by Django 4.1.5 on 2023-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_sourcefiveorg_article_sourcefourorg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
